### ISSUE TITLE
当加入do_predict 参数时，Informer模型报错

### ISSUE THREAD

**Issue by FTWH** [cure-lab/DLinear#2]
我运行了这个脚本:
```python
python -u run_longExp.py \
    --do_predict \
    --is_training 1 \
    --root_path ./dataset/exchange_rate/ \
    --data_path exchange_rate.csv \
    --model_id exchange_96_$pred_len \
    --model Informer \
    --data custom \
    --features M \
    --seq_len 96 \
    --label_len 48 \
    --pred_len $pred_len \
    --e_layers 2 \
    --d_layers 1 \
    --factor 3 \
    --enc_in 8 \
    --dec_in 8 \
    --c_out 8 \
    --des 'Exp' \
    --itr 1 \
    --train_epochs 1 
```

以下是命令行输出：
```shell
Args in experiment:
Namespace(activation='gelu', batch_size=32, c_out=8, checkpoints='./checkpoints/', d_ff=2048, d_layers=1, d_model=512, data='custom', data_path='exchange_rate.csv', dec_in=8, des='Exp', devices='0,1,2,3', distil=True, do_predict=True, dropout=0.05, e_layers=2, embed='timeF', embed_type=0, enc_in=8, factor=3, features='M', freq='h', gpu=0, individual=False, is_training=1, itr=1, label_len=48, learning_rate=0.0001, loss='mse', lradj='type1', model='Informer', model_id='exchange_96_120', moving_avg=25, n_heads=8, num_workers=10, output_attention=False, patience=3, pred_len=120, root_path='./dataset/exchange_rate/', seq_len=96, target='OT', test_flop=False, train_epochs=1, use_amp=False, use_gpu=True, use_multi_gpu=False)
Use GPU: cuda:0
>>>>>>>start training : exchange_96_120_Informer_custom_ftM_sl96_ll48_pl120_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 5096
val 641
test 1398
        iters: 100, epoch: 1 | loss: 0.1259047
        speed: 0.0486s/iter; left time: 2.9178s
Epoch: 1 cost time: 7.077927827835083
Epoch: 1, Steps: 159 | Train Loss: 0.1731077 Vali Loss: 1.1843609 Test Loss: 1.1154609
Validation loss decreased (inf --> 1.184361).  Saving model ...
Updating learning rate to 0.0001
>>>>>>>testing : exchange_96_120_Informer_custom_ftM_sl96_ll48_pl120_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 1398
mse:1.1147866249084473, mae:0.8330836892127991, rse:0.8076118230819702, corr:[0.24108462 0.24678592 0.24392055 0.24274895 0.22613086 0.19483154
 0.1852246  0.2311919  0.25147945 0.251398   0.25062573 0.25143278
 0.25249884 0.2528906  0.25294933 0.22224696 0.2227691  0.21820134
 0.19351245 0.18052752 0.19348595 0.22811855 0.23000397 0.23135814
 0.23256278 0.23463184 0.2364058  0.23792957 0.24070178 0.24167521
 0.2427638  0.2435694  0.2447382  0.24577461 0.24641903 0.24683402
 0.20000085 0.20692253 0.19702218 0.16924712 0.17058574 0.19402179
 0.22150224 0.2209114  0.22238493 0.22340567 0.22408836 0.22468452
 0.22588584 0.22590385 0.22753711 0.22735012 0.21611132 0.18711384
 0.20201753 0.22868772 0.22724001 0.1211504  0.11464377 0.1071261
 0.1140019  0.08780861 0.09210575 0.1355948  0.13518718 0.13542011
 0.13608931 0.13703717 0.13842893 0.13920164 0.13880695 0.1387923
 0.13823137 0.13817464 0.13796644 0.13769653 0.1388846  0.13867514
 0.06931209 0.08072186 0.08846329 0.08113836 0.0582654  0.06327966
 0.09149899 0.0925437  0.09210765 0.09361114 0.09443957 0.09350318
 0.08794986 0.0941087  0.10597284 0.09435335 0.09391043 0.09371786
 0.0939559  0.09545616 0.09653702 0.0536112  0.0556343  0.04710176
 0.03804478 0.01398382 0.04278605 0.06057864 0.06071161 0.06060273
 0.06185045 0.06670263 0.09216081 0.07663918 0.07157028 0.0708864
 0.0719923  0.07214642 0.07216961 0.07173441 0.07221275 0.07557579]
>>>>>>>predicting : exchange_96_120_Informer_custom_ftM_sl96_ll48_pl120_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
pred 1
Traceback (most recent call last):
  File "run_longExp.py", line 126, in <module>
    exp.predict(setting, True)
  File "/DLinear/exp/exp_main.py", line 336, in predict
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
  File "/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/DLinear/models/Informer.py", line 95, in forward
    dec_out = self.dec_embedding(x_dec, x_mark_dec)
  File "/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/DLinear/layers/Embed.py", line 117, in forward
    x = self.value_embedding(x) + self.temporal_embedding(x_mark) + self.position_embedding(x)
RuntimeError: The size of tensor a (96) must match the size of tensor b (168) at non-singleton dimension 1
```

**Comment by mixiancmx** [comment]
你好，这个do_predict参数是用来**读取现有模型，并在未知数据或数据集上测试时**使用的。在用来训练的数据集上使用这个参数是没有意义的（比如你在exchange rate上训练时使用这个参数），因为valid 和 test已经是在exhcange rate内没有用来训练模型的部分上进行测试。
如果你想使用现有训练好的模型在全新的数据上测试，可以使用这个参数。但是同时你也需要修改data_provider/data-loader.py中的Dataset_Pred，使其适配你想测试的新数据

**Comment by FTWH** [comment]
> 你好，这个do_predict参数是在**读取现有模型，并在未知数据或数据集上测试时**使用的。在用来训练的数据集上使用这个参数是没有意义的（比如你在exchange rate上训练时使用了这个参数），因为validate 和 test已经是在exhcange rate数据集内没有用来训练模型的部分上进行测试。 如果你想使用现有训练好的模型在全新的数据上测试，可以使用这个参数。但是同时你也需要修改data_provider/data-loader.py中的Dataset_Pred，使其适配你想测试的新数据

@mixiancmx 感谢，我已经适配数据了，但仍有这个bug。只有Informer会出现，Dlinear以及Autoformer的预测并没有报错。

**Comment by FTWH** [comment]
> > @mixiancmx 感谢，我已经适配数据了，但仍有这个bug。只有Informer会出现，Dlinear以及Autoformer的预测并没有报错。
> > 这个就比较奇怪了，应该是x和x_mark的shape不一致，但是Autoformer和DLinear却能运行？

@mixiancmx 是这样一个情况，可能是Informer模型与您的代码仓库不兼容？我在Informer2020原始仓库运行do_predict也没有问题~ 请问您方便看看吗？

**Comment by mixiancmx** [comment]
> @mixiancmx 是这样一个情况，可能是Informer模型与您的代码仓库不兼容？我在Informer2020原始仓库运行do_predict也没有问题~ 请问您方便看看吗？

我在exchange rate上测试发现，这个问题应该是出在数据处理那，需要在处理数据时保证seq_x和seq_x_mark 的shape一致，以及seq_y 和seq_y_mark的shape一致，位置在`data_provider/data_loader.py`文件下的Dataset_Pred。可能需要根据你想使用的数据修改一下选取的seq_y和seq_y_mark的区间

**Comment by FTWH** [comment]
我认为应该不在数据处理的问题，因为我打印了在计算 outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark) 之前的变量形状，发现他们是一样的。
Informer报错: 
batch_x.shape:torch.Size([1, 96, 8])
batch_x_mark.shape:torch.Size([1, 96, 4])
dec_inp.shape:torch.Size([1, 96, 8])
batch_y_mark.shape:torch.Size([1, 408, 4])

Autoformer正常:
batch_x.shape:torch.Size([1, 96, 8])
batch_x_mark.shape:torch.Size([1, 96, 4])
dec_inp.shape:torch.Size([1, 96, 8])
batch_y_mark.shape:torch.Size([1, 408, 4])

也许是模型本身的问题？

**Comment by mixiancmx** [comment]
> 我认为应该不在数据处理的问题，因为我打印了在计算 outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark) 之前的变量形状，发现他们是一样的。 Informer报错: batch_x.shape:torch.Size([1, 96, 8]) batch_x_mark.shape:torch.Size([1, 96, 4]) dec_inp.shape:torch.Size([1, 96, 8]) batch_y_mark.shape:torch.Size([1, 408, 4])
> 
> Autoformer正常: batch_x.shape:torch.Size([1, 96, 8]) batch_x_mark.shape:torch.Size([1, 96, 4]) dec_inp.shape:torch.Size([1, 96, 8]) batch_y_mark.shape:torch.Size([1, 408, 4])
> 
> 也许是模型本身的问题？
> 
> 另外，除了Informer模型，Transformer模型也会报错。多谢指教！

我刚才忽略了一点，新数据应该是没有batch_y的真实值的，所以Dataset_Pred产生不等长的数据是合理的。但是只有数据等长的情况embedding才能正常运行。Autoformer会对dec_inp重新进行补长，可以参考`Autoformer.py`第107行。但informer和transformer没有，我在predict函数内增加了补长输入的代码，现在应该可以运行了
